### ISSUE TITLE
Unable to filter Refunded transactions only - zero records shown

### ISSUE THREAD

**Issue by RJanata** [quentingosset/PlutusAnalyticsDashboard#26]
Go to Transaction and apply filter for Refunded items. Not items are shown (although there are dozens of refunded transactions).

![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/29975527/b770e5a3-2f92-49df-92f4-6af1a74722bd)

**Comment by quentingosset** [comment]
@RJanata 
Refunded statuses are not official statuses. At first sight when I had refunds, Plutus did not provide exact information on the refund transaction. If you have several refund transactions, can you give me the transaction debug? 
To do this : 
1) on the statements page of my extension, right-click and "inspect element" or CTRL + shift + i
2) click on the little arrow at the top left and select your refund transactions. 
3) copy the data-debug value and paste it here in the comments.

If you have several refund transactions, don't hesitate to put 2-3 so that I can analyse if there is an identical pattern.

![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/6824137/f98e6d0d-a267-475e-9f1a-4b9f67b3b488)

**Comment by RJanata** [comment]
Thanks for the quick response, here are the debug data.
![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/29975527/530c74e7-3b14-4c56-bc3d-a2b0d85c313b)
`{"id":"96dc9246-c51d-40ff-9a48-92a2bb42624a","model":"ContisTransaction","user_id":"0e1c4bcc-caaa-4a20-9f6c-7d47785b19b8","currency":"EUR","amount":1180,"date":"2023-07-09T23:46:21+00:00","type":{"_statementType":["35","45"],"_icon":"/assets/icon-SHOP-58011df9.svg","_name":"REFUNDED"},"is_debit":true,"description":"Refund - CRV*PEDAGGI CARTE ITALIAN, Vilnius, LT CD 6311","__typename":"transactions_view","cashback":[],"status":{"tooltip":{},"value":"refunded","text":"Refunded","style":"bg-slate-100 text-slate-600"},"reason":{},"releaseDate":{},"reward":{"tooltip":{"text":"-"},"value":0},"sortedKeyword":{}}`

**Comment by quentingosset** [comment]
Fixed for next release :)

**Comment by quentingosset** [comment]
Fixed 1.0.4

**Comment by RJanata** [comment]
I can confirm, filtering by Refunded transaction works well in new 1.0.4 version. Thanks for very quick fix :)
