### ISSUE TITLE
Suggestion: Perks page show spend on non-active perks

### ISSUE THREAD

**Issue by dambox** [quentingosset/PlutusAnalyticsDashboard#31]
Hi - perks page is good and shows spend on active perks. It would be really helpful if spend could be shown on nonactive perks - this will make it easy to see of a perk switch is needed.

**Comment by quentingosset** [comment]
I looked, and it's impossible to know that. The transactions don't have any information to say whether it's a transaction linked to a perk or not. The information I have comes from the rewards that I map with the transaction id. So I can't do this functionality because I'm not going to do regexes on all the transaction descriptions to be able to tell that such and such a transaction is an Amazon-type perk etc.
