### ISSUE TITLE
Idea: Pending days

### ISSUE THREAD

**Issue by MarcelErdmann** [quentingosset/PlutusAnalyticsDashboard#42]
It would be really great to display how many days the rewards still need until they are available. So not just a date. But a display of how many days are still pending.  "xx days pending" 

Otherwise I would like to say. Great tool!!!

**Comment by quentingosset** [comment]
The date is already an approximate date based on the 45 days of plutus, the time displayed is also approximate since I'm just using the transaction date +45 days. So adding the days won't give any specific advantage except to add information that will be redundant with the days. 
You can easily count the remaining days with online tools https://www.timeanddate.com/date/duration.html
