### ISSUE TITLE
Display the Number of Transaction of the current Search Criteria next to "All Transactions"

### ISSUE THREAD

**Issue by tschombe** [quentingosset/PlutusAnalyticsDashboard#6]
In the header of the grid, the total Number of Transactions is displayed as  "All Transactions"
If i use Filter criteria it would be nice to see the corresponding number of transactions in the grid next to that number too:

![image](https://user-images.githubusercontent.com/386133/216593842-e6b6d836-f9a4-4bc7-920b-4242e784070a.png)

**Comment by brossboth** [comment]
Adding not only the number of tx's - but also the stats on PLU rewarded, Fiat amount and average PLU price (ie. adding a second line for the full header) for selected filter criteria would be awesome.

**Comment by quentingosset** [comment]
@brossboth @tschombe 
I have made sure that all the values are automatically updated according to the filter. 
I didn't add a second line because it would become too unreadable. 
The idea in the future is that the user will have a general dashboard page where this kind of global information will be included ;)
